# Generated by Django 3.2.4 on 2021-06-13 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 16, 38, 53, 813400)),
        ),
    ]
