# Generated by Django 3.2.4 on 2021-06-13 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 16, 47, 10, 569084)),
        ),
    ]
