# Generated by Django 3.2.4 on 2021-06-14 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_recipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 14, 15, 0, 14, 864690)),
        ),
    ]
